// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/modules/face_geometry/effect_renderer_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/modules/face_geometry/effect_renderer_calculator.proto</summary>
  public static partial class EffectRendererCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/modules/face_geometry/effect_renderer_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EffectRendererCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkBtZWRpYXBpcGUvbW9kdWxlcy9mYWNlX2dlb21ldHJ5L2VmZmVjdF9yZW5k",
            "ZXJlcl9jYWxjdWxhdG9yLnByb3RvEgltZWRpYXBpcGUaLG1lZGlhcGlwZS9m",
            "cmFtZXdvcmsvY2FsY3VsYXRvcl9vcHRpb25zLnByb3RvIs4BCitGYWNlR2Vv",
            "bWV0cnlFZmZlY3RSZW5kZXJlckNhbGN1bGF0b3JPcHRpb25zEhsKE2VmZmVj",
            "dF90ZXh0dXJlX3BhdGgYASABKAkSGwoTZWZmZWN0X21lc2hfM2RfcGF0aBgC",
            "IAEoCTJlCgNleHQSHC5tZWRpYXBpcGUuQ2FsY3VsYXRvck9wdGlvbnMY8Nms",
            "mgEgASgLMjYubWVkaWFwaXBlLkZhY2VHZW9tZXRyeUVmZmVjdFJlbmRlcmVy",
            "Q2FsY3VsYXRvck9wdGlvbnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions), global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions.Parser, new[]{ "EffectTexturePath", "EffectMesh3DPath" }, null, null, new pb::Extension[] { global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FaceGeometryEffectRendererCalculatorOptions : pb::IMessage<FaceGeometryEffectRendererCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FaceGeometryEffectRendererCalculatorOptions> _parser = new pb::MessageParser<FaceGeometryEffectRendererCalculatorOptions>(() => new FaceGeometryEffectRendererCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FaceGeometryEffectRendererCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.EffectRendererCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceGeometryEffectRendererCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceGeometryEffectRendererCalculatorOptions(FaceGeometryEffectRendererCalculatorOptions other) : this() {
      effectTexturePath_ = other.effectTexturePath_;
      effectMesh3DPath_ = other.effectMesh3DPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceGeometryEffectRendererCalculatorOptions Clone() {
      return new FaceGeometryEffectRendererCalculatorOptions(this);
    }

    /// <summary>Field number for the "effect_texture_path" field.</summary>
    public const int EffectTexturePathFieldNumber = 1;
    private readonly static string EffectTexturePathDefaultValue = "";

    private string effectTexturePath_;
    /// <summary>
    /// Defines a path for the visual effect texture file. The effect texture is
    /// later rendered on top of the effect mesh.
    ///
    /// Please be aware about the difference between the CPU texture memory layout
    /// and the GPU texture sampler coordinate space. This renderer follows
    /// conventions discussed here: https://open.gl/textures
    ///
    /// The texture file format must be supported by the OpenCV image decoder. It
    /// must also define either an RGB or an RGBA texture.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EffectTexturePath {
      get { return effectTexturePath_ ?? EffectTexturePathDefaultValue; }
      set {
        effectTexturePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "effect_texture_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEffectTexturePath {
      get { return effectTexturePath_ != null; }
    }
    /// <summary>Clears the value of the "effect_texture_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEffectTexturePath() {
      effectTexturePath_ = null;
    }

    /// <summary>Field number for the "effect_mesh_3d_path" field.</summary>
    public const int EffectMesh3DPathFieldNumber = 2;
    private readonly static string EffectMesh3DPathDefaultValue = "";

    private string effectMesh3DPath_;
    /// <summary>
    /// Defines a path for the visual effect mesh 3D file. The effect mesh is later
    /// "attached" to the face and is driven by the face pose transformation
    /// matrix.
    ///
    /// The mesh 3D file format must be the binary `face_system.Mesh3d` proto.
    ///
    /// If is not present, the runtime face mesh will be used as the effect mesh
    /// - this mode is handy for facepaint effects.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EffectMesh3DPath {
      get { return effectMesh3DPath_ ?? EffectMesh3DPathDefaultValue; }
      set {
        effectMesh3DPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "effect_mesh_3d_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEffectMesh3DPath {
      get { return effectMesh3DPath_ != null; }
    }
    /// <summary>Clears the value of the "effect_mesh_3d_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEffectMesh3DPath() {
      effectMesh3DPath_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FaceGeometryEffectRendererCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FaceGeometryEffectRendererCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EffectTexturePath != other.EffectTexturePath) return false;
      if (EffectMesh3DPath != other.EffectMesh3DPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEffectTexturePath) hash ^= EffectTexturePath.GetHashCode();
      if (HasEffectMesh3DPath) hash ^= EffectMesh3DPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEffectTexturePath) {
        output.WriteRawTag(10);
        output.WriteString(EffectTexturePath);
      }
      if (HasEffectMesh3DPath) {
        output.WriteRawTag(18);
        output.WriteString(EffectMesh3DPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEffectTexturePath) {
        output.WriteRawTag(10);
        output.WriteString(EffectTexturePath);
      }
      if (HasEffectMesh3DPath) {
        output.WriteRawTag(18);
        output.WriteString(EffectMesh3DPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEffectTexturePath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EffectTexturePath);
      }
      if (HasEffectMesh3DPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EffectMesh3DPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FaceGeometryEffectRendererCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasEffectTexturePath) {
        EffectTexturePath = other.EffectTexturePath;
      }
      if (other.HasEffectMesh3DPath) {
        EffectMesh3DPath = other.EffectMesh3DPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EffectTexturePath = input.ReadString();
            break;
          }
          case 18: {
            EffectMesh3DPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EffectTexturePath = input.ReadString();
            break;
          }
          case 18: {
            EffectMesh3DPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the FaceGeometryEffectRendererCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions>(323693808, pb::FieldCodec.ForMessage(2589550466, global::Mediapipe.FaceGeometryEffectRendererCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
